# Generated by Django 2.2.16 on 2023-05-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=512, null=True, verbose_name='Описание')),
                ('slug', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Строения',
                'verbose_name_plural': 'Строения',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='BuildingInProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Строящиеся здания',
                'verbose_name_plural': 'Строящиеся здания',
            },
        ),
        migrations.CreateModel(
            name='BuildingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Требования к постройкам',
                'verbose_name_plural': 'Требования к постройкам',
                'ordering': ('building', 'requirement'),
            },
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('order', models.SmallIntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('base_time', models.DurationField(blank=True, null=True)),
                ('base_gold', models.SmallIntegerField(verbose_name='Золото')),
                ('base_wood', models.SmallIntegerField(verbose_name='Дерево')),
                ('base_stone', models.SmallIntegerField(verbose_name='Камень')),
            ],
            options={
                'verbose_name': 'Тип строения',
                'verbose_name_plural': 'Типы строений',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('bonus', models.CharField(max_length=256, verbose_name='Бонус')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('slug', models.CharField(max_length=20, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='fractions/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фракция',
                'verbose_name_plural': 'Фракции',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_amount', models.FloatField(default=100)),
                ('wood_amount', models.FloatField(default=2)),
                ('stone_amount', models.FloatField(default=2)),
                ('gold_income', models.IntegerField(default=10)),
                ('wood_income', models.IntegerField(default=1)),
                ('stone_income', models.IntegerField(default=1)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ресурсы',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='UserBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='уровень')),
                ('building_time', models.DurationField(blank=True, null=True)),
                ('gold', models.BigIntegerField(verbose_name='Золото')),
                ('wood', models.BigIntegerField(verbose_name='Дерево')),
                ('stone', models.BigIntegerField(verbose_name='Stone')),
                ('slug', models.CharField(max_length=32)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buildings', to='towns.Building', verbose_name='строение')),
            ],
            options={
                'verbose_name': 'Построенные здания',
                'verbose_name_plural': 'Построенные здания',
                'ordering': ('building',),
            },
        ),
        migrations.CreateModel(
            name='UserBuildingRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_building', to='towns.UserBuilding', verbose_name='Здание')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requirements', to='towns.Building', verbose_name='Требование')),
            ],
            options={
                'verbose_name': 'Требования для зданий построенные игроком',
                'verbose_name_plural': 'Требования для зданий построенные игроком',
                'ordering': ('building', 'requirement'),
            },
        ),
    ]
