# Generated by Django 2.2.16 on 2023-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('bonus', models.CharField(max_length=256, verbose_name='Бонус')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='fractions/', verbose_name='Картинка')),
            ],
        ),
    ]
