# Generated by Django 2.2.16 on 2023-02-28 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fractions',
            options={'verbose_name': 'Фракция', 'verbose_name_plural': 'Фракции'},
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_amount', models.BigIntegerField(default=0)),
                ('wood_amount', models.BigIntegerField(default=0)),
                ('stone_amount', models.BigIntegerField(default=0)),
                ('gold_income', models.BigIntegerField(default=1)),
                ('wood_income', models.BigIntegerField(default=1)),
                ('stone_income', models.BigIntegerField(default=1)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete='Ресурсы', related_name='resource', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
    ]
