# Generated by Django 2.2.16 on 2023-02-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_auto_20230228_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name': 'Ресурсы', 'verbose_name_plural': 'Ресурсы'},
        ),
        migrations.AlterField(
            model_name='resources',
            name='gold_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='gold_income',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stone_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stone_income',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resources',
            name='wood_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='wood_income',
            field=models.IntegerField(default=1),
        ),
    ]
