# Generated by Django 2.2.16 on 2023-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_auto_20230301_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='gold_amount',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='resources',
            name='gold_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stone_amount',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='resources',
            name='stone_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='wood_amount',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='resources',
            name='wood_income',
            field=models.IntegerField(default=0),
        ),
    ]
