# Generated by Django 2.2.16 on 2023-03-01 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towns', '0004_auto_20230301_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='buildings/', verbose_name='Изображение')),
                ('top', models.SmallIntegerField()),
                ('left', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fractions',
            name='image',
            field=models.ImageField(blank=True, upload_to='fractions/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to=settings.AUTH_USER_MODEL, verbose_name='Ресурсы'),
        ),
        migrations.CreateModel(
            name='BuildingsCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('wood', models.IntegerField()),
                ('stone', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='towns.Buildings', verbose_name='Строение')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingsCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscompleted', to='towns.Buildings', verbose_name='строение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingscompleted', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='fraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='towns.Fractions', verbose_name='Фракция'),
        ),
    ]
