# Generated by Django 2.2.16 on 2023-05-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_auto_20230516_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='gold_limit',
            field=models.BigIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='resource',
            name='stone_limit',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='resource',
            name='wood_limit',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='gold_amount',
            field=models.FloatField(default=1000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='gold_income',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='stone_amount',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='resource',
            name='stone_income',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='resource',
            name='wood_amount',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='resource',
            name='wood_income',
            field=models.IntegerField(default=3),
        ),
    ]
