# Generated by Django 2.2.16 on 2023-06-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_auto_20230517_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraction',
            name='image',
        ),
    ]
