# Generated by Django 2.2.16 on 2023-02-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fraction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fractions', to='towns.Fractions', verbose_name='Фракция'),
        ),
    ]
